app:
  name: gateway # change
  hostname: localhost # change
  server-port: 8181
  eureka:
    hostname: localhost # change
    port: 8761
  version: v1
  user-service:
    name: user
    context-path: api/${app.user-service.name}/${app.version}
  order-service:
    name: order
    context-path: api/${app.order-service.name}/${app.version}
  inventory-service:
    name: inventory
    context-path: api/${app.inventory-service.name}/${app.version}
  payment-service:
    name: payment
    context-path: api/${app.payment-service.name}/${app.version}
  notification-service:
    name: notification
    context-path: api/${app.notification-service.name}/${app.version}
  springdoc:
    context-path: api-docs
  zipkin:
    hostname: localhost # change
    server-port: 9411
    context-path: api/v2/spans
    endpoint: http://${app.zipkin.hostname}:${app.zipkin.server-port}/${app.zipkin.context-path}
  keycloak:
    hostname: localhost # change
    port: 8090
  microservices-admin-client:
    client-id: microservices-admin-client
    client-secret: 123456789

security:
  enabled: true
  skip-urls:
    - /eureka/**
    - /${app.user-service.context-path}/**
    - /${app.order-service.context-path}/**
    - /${app.inventory-service.context-path}/**
    - /${app.payment-service.context-path}/**
    - /${app.notification-service.context-path}/**
    - /swagger-ui.html
    - /webjars/swagger-ui/**
    - /v3/api-docs/**
    - /actuator/**
    - /error/**
    - /auth/**

spring:
  application:
    name: ${app.name}-service
  profiles:
    active: local
  main:
    web-application-type: reactive
  security:
    oauth2:
      client:
        provider:
          keycloak:
            authorization-uri: http://${app.keycloak.hostname}:${app.keycloak.port}/realms/spring-boot-microservices-realm/protocol/openid-connect/auth
            token-uri: http://${app.keycloak.hostname}:${app.keycloak.port}/realms/spring-boot-microservices-realm/protocol/openid-connect/token
            user-info-uri: http://${app.keycloak.hostname}:${app.keycloak.port}/realms/spring-boot-microservices-realm/protocol/openid-connect/userinfo
            user-name-attribute: sub
            jwk-set-uri: http://${app.keycloak.hostname}:${app.keycloak.port}/realms/spring-boot-microservices-realm/protocol/openid-connect/certs
            issuer-uri: http://${app.keycloak.hostname}:${app.keycloak.port}/realms/spring-boot-microservices-realm
        registration:
          microservices-admin-client:
            provider: keycloak
            client-id: ${app.microservices-admin-client.client-id}
            client-secret: ${app.microservices-admin-client.client-secret}
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - profile
              - email
              - roles
              - read
              - write
            client-name: Microservices Admin Client

  cloud:
    gateway:
      globalcors:
        '[/**]':
          allowedOrigins: "*"
          allowedMethods: "*"
      discovery:
        locator:
          enabled: true
      default-filters:
        - TokenRelay
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/order/**
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/inventory/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notification/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payment/**
        - id: discovery-serverice
          uri: http://${app.eureka.hostname}:${app.eureka.port}
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        - id: discovery-serverice-static
          uri: http://${app.eureka.hostname}:${app.eureka.port}
          predicates:
            - Path=/eureka/**

server:
  port: ${app.server-port}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka.hostname}:${app.eureka.port}/eureka
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5

springdoc:
  swagger-ui:
    urls:
      - name: user-service
        url: http://${app.hostname}:${app.server-port}/${app.user-service.context-path}/${app.springdoc.context-path}
      - name: order-service
        url: http://${app.hostname}:${app.server-port}/${app.order-service.context-path}/${app.springdoc.context-path}
      - name: inventory-service
        url: http://${app.hostname}:${app.server-port}/${app.inventory-service.context-path}/${app.springdoc.context-path}
      - name: payment-service
        url: http://${app.hostname}:${app.server-port}/${app.payment-service.context-path}/${app.springdoc.context-path}
      - name: notification-service
        url: http://${app.hostname}:${app.server-port}/${app.notification-service.context-path}/${app.springdoc.context-path}

    path: /swagger-ui.html

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway: TRACE
#    org.springframework.cloud.gateway: INFO
  pattern:
    level: "%5p[${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

management:
  tracing:
    enabled: true
    propagation:
      type: b3
    sampling:
      probability: 1.0
  endpoint:
    health:
      show-details: always
  health:
    diskspace:
      enabled: true
    db:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  zipkin:
    tracing:
      endpoint: ${app.zipkin.endpoint}



